### PR TITLE
EAS-2074 : Make FSRT more performant with a definition analysis map without projections

### PR DESCRIPTION
**Pull request by gersbach**
Don't worry, not another 500 line PR 😅. This includes the commit of the previous PR. But, might as well open this.... 😄

### CODE REVIEW

**Comment by gersbach** [comment]
this has been fixed to include a hash map instead of the btree map when there are no projections. thank you!

**Comment by gersbach** [comment]
Let me validate that this still works with the objects.

**Comment by gersbach** [comment]
Ok, I validated it works with the test cases that have been looked at. 

I noticed a false negative case, where 

```

    let h = { headers: { authorization: 'foo' } };
    let c = h
   c.headers = { };
   c.headers.authorization = "test"

```

I'll look at this after I fix the other bug assigned to me.

**Review by jwong101 — APPROVED** [review]
Approved. Once you rebase this, I'll merge it in.

**Comment by gersbach** [comment]
> Approved. Once you rebase this, I'll merge it in.

rebased! thank you!

**Pull request merged**
